docs: update guides on handling number modifier
ghostty-org/website pull request #170
Opened 2024-12-27 13:40 UTC by hisamafahri

Based off of: https://github.com/ghostty-org/ghostty/discussions/3252

2024-12-27 23:21 UTC, BrandonRomano commented on docs/config/reference.mdx
> +  * for number modifier, write them out in letters instead of the actual
This is a generated file; would you mind submitting this as a PR upstream to Ghostty?

We're going to make this more clear (#183).

https://github.com/ghostty-org/ghostty/blob/bee21880149129f9373a35e9df0d39c223481709/src/config/Config.zig#L780

2024-12-27 23:21 UTC, BrandonRomano requested changes
See inline comment above

2024-12-28 06:34 UTC, hisamafahri commented
@BrandonRomano, updated the code and opened a PR (https://github.com/ghostty-org/ghostty/pull/3664) on the upstream repo

2025-01-01 03:15 UTC, BrandonRomano reviewed
Commenting to remove my rejection; I’ll leave to someone on the docs side of the house to approve / merge in!

Thank you for adjusting 🙇

2025-01-01 03:16 UTC, BrandonRomano approved these changes

2025-01-01 03:58 UTC, mitchellh commented
No longer necessary, Ghostty 1.0.1 treats this equally.

2025-01-01 03:59 UTC, mitchellh commented
###

2025-01-01 03:59 UTC, closed without merging